# Generated by Django 6.0.3 on 2026-05-12 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_email', models.EmailField(blank=True, help_text='Email for alerts (uses account email if blank)', max_length=254, null=True)),
                ('notify_website_changes', models.BooleanField(default=True)),
                ('notify_new_jobs', models.BooleanField(default=True)),
                ('notify_follower_change', models.BooleanField(default=True)),
                ('notify_new_pages', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
