# Generated by Django 4.2.7 on 2025-11-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_url", models.URLField()),
                (
                    "scraping_frequency",
                    models.CharField(default="daily", max_length=20),
                ),
                (
                    "selectors",
                    models.JSONField(
                        default=dict, help_text="CSS selectors for scraping"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        default=dict, help_text="HTTP headers for requests"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_configs",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraping Config",
                "verbose_name_plural": "Scraping Configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_scraped", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "execution_time",
                    models.FloatField(help_text="Execution time in seconds"),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scraping.scrapingconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraping Log",
                "verbose_name_plural": "Scraping Logs",
                "ordering": ["-completed_at"],
            },
        ),
    ]
