# Generated by Django 4.2.7 on 2026-05-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monitoring", "0003_competitor_change_count_htmldifference_llm_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("linkedin", "LinkedIn"), ("twitter", "Twitter")],
                        max_length=20,
                    ),
                ),
                ("follower_count", models.PositiveIntegerField(blank=True, null=True)),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_snapshots",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["competitor", "platform", "-recorded_at"],
                        name="social_medi_competi_82540c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("linkedin", "LinkedIn"), ("twitter", "Twitter")],
                        max_length=20,
                    ),
                ),
                (
                    "post_id",
                    models.CharField(
                        help_text="Platform-native ID for deduplication", max_length=255
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("article", "Article"),
                            ("update", "Update"),
                            ("job", "Job"),
                        ],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("post_url", models.URLField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("author_headline", models.CharField(blank=True, max_length=500)),
                ("num_likes", models.PositiveIntegerField(default=0)),
                ("num_comments", models.PositiveIntegerField(default=0)),
                ("num_shares", models.PositiveIntegerField(default=0)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(
                        fields=["competitor", "platform", "-posted_at"],
                        name="social_medi_competi_94f727_idx",
                    ),
                    models.Index(
                        fields=["competitor", "-scraped_at"],
                        name="social_medi_competi_455c51_idx",
                    ),
                ],
                "unique_together": {("competitor", "platform", "post_id")},
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="LinkedIn job ID for deduplication", max_length=255
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("employment_type", models.CharField(blank=True, max_length=100)),
                ("seniority_level", models.CharField(blank=True, max_length=100)),
                ("job_function", models.CharField(blank=True, max_length=255)),
                ("industries", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("job_url", models.URLField(blank=True, null=True)),
                ("apply_url", models.URLField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False when job no longer appears in scrape",
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["competitor", "-first_seen_at"],
                        name="social_medi_competi_f4bbd7_idx",
                    ),
                    models.Index(
                        fields=["competitor", "is_active"],
                        name="social_medi_competi_c69893_idx",
                    ),
                    models.Index(
                        fields=["is_new"], name="social_medi_is_new_44c01c_idx"
                    ),
                ],
                "unique_together": {("competitor", "job_id")},
            },
        ),
    ]
