# Generated by Django 4.2.7 on 2026-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediasnapshot",
            name="platform",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter"),
                ],
                max_length=20,
            ),
        ),
    ]
