# Generated by Django 4.2.7 on 2025-11-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("results_count", models.IntegerField(default=0)),
                (
                    "top_competitors",
                    models.JSONField(
                        default=list, help_text="List of competitor IDs in results"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Response time in seconds"),
                ),
                ("similarity_threshold", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Query Log",
                "verbose_name_plural": "Query Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VectorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vector_id",
                    models.CharField(
                        help_text="ID in Milvus", max_length=255, unique=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(default="sentence-transformers", max_length=100),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        default=0, help_text="Chunk number for large documents"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_documents",
                        to="monitoring.competitormetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vector Document",
                "verbose_name_plural": "Vector Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vector_id"], name="rag_vectord_vector__51f49d_idx"
                    )
                ],
            },
        ),
    ]
