# Generated by Django 4.2.7 on 2025-11-16 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                (
                    "retrieved_chunks",
                    models.JSONField(
                        default=list, help_text="Retrieved chunk IDs and scores"
                    ),
                ),
                ("generated_answer", models.TextField(blank=True)),
                (
                    "retrieval_time",
                    models.FloatField(help_text="Time to retrieve chunks (seconds)"),
                ),
                (
                    "generation_time",
                    models.FloatField(help_text="Time to generate answer (seconds)"),
                ),
                (
                    "total_time",
                    models.FloatField(help_text="Total response time (seconds)"),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        default=5, help_text="Number of chunks retrieved"
                    ),
                ),
                ("model_used", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "RAG Query",
                "verbose_name_plural": "RAG Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="Original JSON filename", max_length=500
                    ),
                ),
                ("competitor_name", models.CharField(db_index=True, max_length=100)),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "chunk_text",
                    models.TextField(help_text="Text chunk for RAG retrieval"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(default=0, help_text="Position in document"),
                ),
                (
                    "chunk_size",
                    models.IntegerField(help_text="Number of characters in chunk"),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="384-dimensional embedding vector",
                        size=384,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "ordering": ["competitor_name", "source_file", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["competitor_name", "created_at"],
                        name="rag_documen_competi_659fd6_idx",
                    ),
                    models.Index(
                        fields=["source_file"], name="rag_documen_source__05f94f_idx"
                    ),
                ],
            },
        ),
    ]
