# Generated by Django 4.2.7 on 2026-03-07 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0002_ragquery_documentchunk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentChunk",
        ),
        migrations.DeleteModel(
            name="RAGQuery",
        ),
    ]
