# Generated by Django 4.2.7 on 2025-11-16 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website_base_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor",
                "verbose_name_plural": "Competitors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_tasks",
                        to="monitoring.competitor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoring Task",
                "verbose_name_plural": "Monitoring Tasks",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="FilteredLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "links",
                    models.JSONField(default=list, help_text="List of filtered URLs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filtered_links",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtered Links",
                "verbose_name_plural": "Filtered Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "links",
                    models.JSONField(default=list, help_text="List of extracted URLs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_links",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Links",
                "verbose_name_plural": "Extracted Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyScraperLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "links",
                    models.JSONField(default=list, help_text="Links to scrape daily"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_scraper_links",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Scraper Links",
                "verbose_name_plural": "Daily Scraper Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Extracted metadata for RAG"
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor Metadata",
                "verbose_name_plural": "Competitor Metadata",
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["competitor", "-extracted_at"],
                        name="monitoring__competi_5f63dd_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompetitorHTML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("html_content", models.TextField(help_text="Raw HTML content")),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="html_content",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor HTML",
                "verbose_name_plural": "Competitor HTML",
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["competitor", "-scraped_at"],
                        name="monitoring__competi_932a44_idx",
                    ),
                    models.Index(fields=["url"], name="monitoring__url_d30a78_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="competitor",
            index=models.Index(
                fields=["user", "is_deleted"], name="monitoring__user_id_c6a2e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competitor",
            index=models.Index(
                fields=["website_base_url"], name="monitoring__website_568bff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="competitor",
            unique_together={("user", "website_base_url")},
        ),
    ]
