# Generated by Django 4.2.7 on 2025-12-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HTMLSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "html_content",
                    models.TextField(help_text="Full HTML content snapshot"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA256 hash of content for quick comparison",
                        max_length=64,
                    ),
                ),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="html_snapshots",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "HTML Snapshot",
                "verbose_name_plural": "HTML Snapshots",
                "ordering": ["-snapshot_at"],
            },
        ),
        migrations.CreateModel(
            name="HTMLDifference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("added", "Content Added"),
                            ("removed", "Content Removed"),
                            ("modified", "Content Modified"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diff_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Summary of changes: added_sections, removed_sections, modified_sections",
                    ),
                ),
                (
                    "detailed_diff",
                    models.JSONField(
                        default=list,
                        help_text="Detailed line-by-line or block-by-block differences",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_significant",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this change is significant enough for RAG update",
                    ),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="html_differences",
                        to="monitoring.competitor",
                    ),
                ),
                (
                    "new_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differences_as_new",
                        to="monitoring.htmlsnapshot",
                    ),
                ),
                (
                    "old_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differences_as_old",
                        to="monitoring.htmlsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "HTML Difference",
                "verbose_name_plural": "HTML Differences",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="htmlsnapshot",
            index=models.Index(
                fields=["competitor", "url", "-snapshot_at"],
                name="monitoring__competi_9f3d49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="htmlsnapshot",
            index=models.Index(
                fields=["content_hash"], name="monitoring__content_6864e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="htmldifference",
            index=models.Index(
                fields=["competitor", "url", "-detected_at"],
                name="monitoring__competi_65904b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="htmldifference",
            index=models.Index(
                fields=["is_significant"], name="monitoring__is_sign_43ad5d_idx"
            ),
        ),
    ]
