# Generated by Django 4.2.7 on 2026-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_htmlsnapshot_htmldifference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="change_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Running total of detected changes"
            ),
        ),
        migrations.AddField(
            model_name="htmldifference",
            name="llm_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="LLM-generated human-readable summary of the changes",
            ),
        ),
    ]
