# Generated by Django 4.2.7 on 2026-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_competitor_change_count_htmldifference_llm_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="stock_symbol",
            field=models.CharField(
                blank=True,
                help_text="Stock ticker symbol (e.g. CRM, MSFT) for FMP data",
                max_length=20,
                null=True,
            ),
        ),
    ]
