# Generated by Django 4.2.7 on 2026-05-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_competitor_stock_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=2000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='monitoring.competitor')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['competitor', '-published_at'], name='monitoring__competi_8974ff_idx')],
                'unique_together': {('competitor', 'url')},
            },
        ),
    ]
