# Generated by Django 4.2.7 on 2026-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_add_newsarticle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
