# Generated by Django 4.2.7 on 2026-05-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_add_description_to_newsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='description',
        ),
    ]
