# Generated by Django 4.2.7 on 2026-05-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0009_competitor_onboarding_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scraping", "Scraping Pages"),
                    ("indexing", "Building AI Index"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                ],
                default="pending",
                help_text="Tracks initial data pipeline progress after competitor is added",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="htmldifference",
            name="is_significant",
            field=models.BooleanField(
                default=False,
                help_text="True only for critical business-impacting changes",
            ),
        ),
    ]
