# Generated by Django 4.2.7 on 2026-05-31 10:48

import apps.monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0011_htmldifference_is_onboarding_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[apps.monitoring.models.validate_facebook_url],
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[apps.monitoring.models.validate_instagram_url],
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[apps.monitoring.models.validate_linkedin_url],
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[apps.monitoring.models.validate_twitter_url],
            ),
        ),
    ]
