# Generated by Django 4.2.7 on 2025-11-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trend_type", models.CharField(max_length=50)),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("up", "Upward"),
                            ("down", "Downward"),
                            ("stable", "Stable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Confidence score 0-1"),
                ),
                ("analysis_data", models.JSONField(default=dict)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Analysis",
                "verbose_name_plural": "Trend Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=50)),
                ("metric_value", models.FloatField()),
                ("metric_metadata", models.JSONField(blank=True, default=dict)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="monitoring.competitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor Metric",
                "verbose_name_plural": "Competitor Metrics",
                "ordering": ["-date", "competitor"],
                "indexes": [
                    models.Index(
                        fields=["competitor", "metric_type", "-date"],
                        name="analytics_c_competi_d3518d_idx",
                    )
                ],
            },
        ),
    ]
